name: flutter_app
description: Budget Book

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  keep_screen_on: ^2.1.0
  double_back_to_close_app: ^2.1.0
  shared_preferences: ^2.1.1
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.4.0
  supabase_flutter: ^1.10.0
  flutter_dotenv: ^5.0.2
  settings_ui: ^2.0.2
  intl: any
  uni_links: ^0.5.1
  connectivity_plus: ^3.0.6
  logger: ^1.3.0
  form_validator: ^2.1.1
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_gauges: ^21.2.4
  intl_utils: ^2.8.2
  provider: ^6.0.5
  math_expressions: ^2.4.0
  syncfusion_flutter_charts: ^21.2.4
  community_material_icon: ^5.9.55
  collection: ^1.16.0
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.16
  flutter_typeahead: ^3.2.7
  flutter_shake_animated: ^0.0.5
  package_info_plus: ^4.2.0

dev_dependencies:

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/splash.png
    - assets/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#  fonts:

# run 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  image_path: "assets/logo.png"
  ios: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/logo-background.png"
  adaptive_icon_foreground: "assets/logo.png"

#run 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  color: "#303030"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleToFill